
-- ========================================================
-- إعداد قاعدة بيانات Supabase لنظام (Wasla Tech Administration)
-- لتأمين النظام للعمل على Vercel
-- ========================================================

-- 1. جدول الأعضاء (Members)
CREATE TABLE IF NOT EXISTS public.members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    full_name TEXT NOT NULL,
    team TEXT,
    completion_rank INT DEFAULT 0,
    team_notes TEXT,
    residence TEXT,
    work_conditions TEXT,
    bio TEXT,
    phone TEXT,
    device TEXT,
    gender TEXT,
    meeting_attendance TEXT,
    work_status TEXT,
    can_go_alexandria BOOLEAN DEFAULT false
);

-- 2. جدول الملاحظات العام (Notes)
CREATE TABLE IF NOT EXISTS public.notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    text TEXT NOT NULL,
    author TEXT,
    author_role TEXT,
    date TEXT,
    team TEXT,
    target_team TEXT,
    target_member_id BIGINT,
    target_name TEXT
);

-- 3. جدول المهام الديناميكي (Tasks) 
-- (تمت إضافته للتماشى مع ميزة التكليفات الجديدة)
CREATE TABLE IF NOT EXISTS public.tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    has_deadline BOOLEAN DEFAULT false,
    deadline_date TEXT,
    assigned_to JSONB, -- Array of IDs or "ALL"
    tracking JSONB DEFAULT '{}'::jsonb -- Stores tracking statuses and task-specific notes
);

-- 4. إعدادات الأمان والتراخيص (RLS - Row Level Security)
-- لحماية بياناتك عندما يتم إطلاق النظام حياً على Vercel

ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;

-- سماح لجميع المستخدمين المسجلين الدخول بعمليات القراءة والكتابة
CREATE POLICY "Full access to members for authenticated users" 
ON public.members FOR ALL TO authenticated USING (true);

CREATE POLICY "Full access to notes for authenticated users" 
ON public.notes FOR ALL TO authenticated USING (true);

CREATE POLICY "Full access to tasks for authenticated users" 
ON public.tasks FOR ALL TO authenticated USING (true);

-- (اختياري) السماح بالمشاهدة المجهولة في حال أردت أن يقوم الزوار بالقراءة فقط:
-- CREATE POLICY "Enable read access for all users" ON public.members FOR SELECT USING (true);
-- CREATE POLICY "Enable read access for all users" ON public.tasks FOR SELECT USING (true);
