-- ========================================================
-- إعداد قاعدة بيانات Supabase لنظام (Wasla Tech Administration v2)
-- النسخة المحصّنة (Security-Hardened)
--
-- لقاعدة موجودة بالفعل بالنسخة القديمة: استخدم
--   backend/migrations/0001_security_hardening.sql
-- بدلاً من هذا الملف (هذا الملف للتثبيت الجديد الكامل فقط).
--
-- قواعد الأمان المعتمدة هنا:
--   1. الإدارة (authenticated): صلاحيات كاملة عبر RLS.
--   2. بوابة الأعضاء (anon): قراءة أعمدة محددة فقط (بدون هاتف/نوع/سكن/ملاحظات خاصة)
--      + تحديث عمود tracking في المهام فقط (عمود واحد ولا شيء غيره).
--   3. الاعتماد (approved) حق إداري حصرياً — Trigger يمنع anon من اعتماد أي مهمة.
--   4. دوال الـ Vault (مفتاح Groq) قاصرة على service_role — لا يمكن لأي زائر أو
--      مستخدم عادي استدعاؤها عبر PostgREST.
-- ========================================================

-- 0) الجداول ------------------------------------------------

CREATE TABLE IF NOT EXISTS public.members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    email TEXT UNIQUE NOT NULL,
    full_name TEXT NOT NULL,
    team TEXT,
    completion_rank INT DEFAULT 0 CHECK (completion_rank >= 0 AND completion_rank <= 100),
    team_notes TEXT,
    residence TEXT,
    work_conditions TEXT,
    bio TEXT,
    phone TEXT,
    device TEXT,
    gender TEXT,
    meeting_attendance TEXT,
    work_status TEXT DEFAULT 'active',
    can_go_alexandria BOOLEAN DEFAULT false
);

CREATE INDEX IF NOT EXISTS idx_members_email ON public.members (email);
CREATE INDEX IF NOT EXISTS idx_members_team ON public.members (team);

CREATE TABLE IF NOT EXISTS public.notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    text TEXT NOT NULL,
    author TEXT,
    author_role TEXT,
    date TEXT,
    team TEXT,
    target_team TEXT,
    target_member_id BIGINT REFERENCES public.members(id) ON DELETE SET NULL,
    target_name TEXT
);

CREATE INDEX IF NOT EXISTS idx_notes_target_member ON public.notes (target_member_id);

CREATE TABLE IF NOT EXISTS public.tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    has_deadline BOOLEAN DEFAULT false,
    deadline_date TEXT,
    assigned_to JSONB DEFAULT '[]'::jsonb, -- Array of Member IDs or "ALL"
    tracking JSONB DEFAULT '{}'::jsonb    -- Map of { [memberId]: { status, note, submission_url, updated_at } }
);

CREATE INDEX IF NOT EXISTS idx_tasks_created_at ON public.tasks (created_at DESC);

CREATE TABLE IF NOT EXISTS public.whatsapp_settings (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    enabled BOOLEAN NOT NULL DEFAULT false,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by TEXT
);
INSERT INTO public.whatsapp_settings (id, enabled) VALUES (1, false) ON CONFLICT (id) DO NOTHING;
ALTER TABLE public.whatsapp_settings ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.whatsapp_settings FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.whatsapp_settings TO service_role;

-- 1) تفعيل RLS ----------------------------------------------

ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;

-- 2) السياسات: الإدارة (authenticated) ----------------------

DROP POLICY IF EXISTS "Admins full access to members" ON public.members;
DROP POLICY IF EXISTS "Full access to members for authenticated users" ON public.members;
CREATE POLICY "Admins full access to members"
ON public.members FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Admins full access to notes" ON public.notes;
DROP POLICY IF EXISTS "Full access to notes for authenticated users" ON public.notes;
CREATE POLICY "Admins full access to notes"
ON public.notes FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Admins full access to tasks" ON public.tasks;
DROP POLICY IF EXISTS "Full access to tasks for authenticated users" ON public.tasks;
CREATE POLICY "Admins full access to tasks"
ON public.tasks FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 3) السياسات: بوابة الأعضاء (anon) -------------------------
-- ملاحظة: التقييد الحقيقي للأعمدة يتم في القسم 4 (Column-level GRANTs)
-- فالسياسة تشمل الصفوف، والـ GRANT يشمل الأعمدة — الطبقتان تعملان معاً.

DROP POLICY IF EXISTS "Anon read members by email" ON public.members;
CREATE POLICY "Anon members login lookup"
ON public.members FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "Anon read tasks" ON public.tasks;
CREATE POLICY "Anon read tasks"
ON public.tasks FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "Anon update task tracking" ON public.tasks;
CREATE POLICY "Anon update own task tracking"
ON public.tasks FOR UPDATE TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Anon read notes" ON public.notes;
CREATE POLICY "Anon read notes"
ON public.notes FOR SELECT TO anon USING (true);

-- 4) صلاحيات الأعمدة (الحزام الثاني بعد RLS) ----------------
-- هذا القسم هو ما يمنع تسريب البيانات الشخصية فعلياً:
--  - بلااته: anon لا يرى phone / gender / residence / work_conditions / team_notes
--  - المهام: anon لا يمكنه تعديل أي عمود سوى tracking (لا عنوان ولا قائمة مكلفين)

REVOKE ALL ON public.members, public.tasks, public.notes FROM anon;

GRANT SELECT (id, created_at, email, full_name, team, bio, device, meeting_attendance, work_status, completion_rank, can_go_alexandria)
    ON public.members TO anon;

GRANT SELECT ON public.tasks TO anon;
GRANT UPDATE (tracking) ON public.tasks TO anon;
GRANT SELECT ON public.notes TO anon;

-- 5) Trigger: منع الاعتماد الذاتي للعضو ----------------------
-- أي عضو (anon) يحاول تحويل حالته إلى approved في tracking يُرفض على مستوى القاعدة.
-- الاعتماد ومنح النقاط حق إداري (authenticated) حصرياً.

CREATE OR REPLACE FUNCTION public.guard_anon_tracking_update()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_key text;
    v_val jsonb;
BEGIN
    IF current_setting('role', true) = 'anon' THEN
        FOR v_key, v_val IN
            SELECT key, value FROM jsonb_each(coalesce(NEW.tracking, '{}'::jsonb))
        LOOP
            IF v_val->>'status' = 'approved'
               AND coalesce(OLD.tracking, '{}'::jsonb) -> v_key ->> 'status'
                   IS DISTINCT FROM 'approved'
            THEN
                RAISE EXCEPTION
                    'ADMIN_APPROVAL_FORBIDDEN: لا يمكن للأعضاء اعتماد مهامهم بأنفسهم — الاعتماد حق إداري فقط.';
            END IF;
        END LOOP;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_tasks_guard_anon ON public.tasks;
CREATE TRIGGER trg_tasks_guard_anon
BEFORE UPDATE ON public.tasks
FOR EACH ROW
EXECUTE FUNCTION public.guard_anon_tracking_update();

-- 6) دوال الـ Vault: مفتاح Groq -----------------------------
-- قاصرة على service_role (الـ Edge Function فقط يستخدمها بهوية خدمية).
-- زوّد المفتاح مرة واحدة من Supabase SQL Editor:
--   SELECT public.set_groq_key('gsk_...');
-- ملاحظة: SQL Editor يعمل بهوية postgres (المالك) فلا يعوقه الـ REVOKE.

CREATE OR REPLACE FUNCTION public.set_groq_key(p_key text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_id uuid;
BEGIN
    SELECT id INTO v_id FROM vault.decrypted_secrets WHERE name = 'groq_api_key';
    IF v_id IS NOT NULL THEN
        PERFORM vault.delete_secret(v_id);
    END IF;
    PERFORM vault.create_secret(p_key, 'groq_api_key');
END;
$$;

CREATE OR REPLACE FUNCTION public.get_groq_key_from_vault()
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_secret text;
BEGIN
    SELECT secret INTO v_secret
    FROM vault.decrypted_secrets
    WHERE name = 'groq_api_key';
    RETURN v_secret;
END;
$$;

REVOKE ALL ON FUNCTION public.set_groq_key(text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.get_groq_key_from_vault() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.set_groq_key(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_groq_key_from_vault() TO service_role;
