import type { Member, Task } from '../types/db';

export const DEFAULT_MEMBERS: Member[] = [
  {
    id: 1,
    created_at: new Date(Date.now() - 86400000 * 10).toISOString(),
    email: 'ahmed@wasla.com',
    full_name: 'أحمد محمود',
    team: 'تطوير البرمجيات',
    completion_rank: 92,
    team_notes: 'عضو متميز، ملتزم بالمواعيد',
    residence: 'القاهرة - المعادي',
    work_conditions: 'متاح للعمل المكتبي والميداني',
    bio: 'Frontend Lead & React Specialist',
    phone: '01012345678',
    device: 'لابتوب Core i7',
    gender: 'ذكر',
    meeting_attendance: 'منتظم',
    work_status: 'active',
    can_go_alexandria: true,
  },
  {
    id: 2,
    created_at: new Date(Date.now() - 86400000 * 9).toISOString(),
    email: 'sara@wasla.com',
    full_name: 'سارة علي',
    team: 'التصميم',
    completion_rank: 88,
    team_notes: 'تصاميمها مبتكرة',
    residence: 'الإسكندرية - سموحة',
    work_conditions: 'جاهزة للفعاليات الميدانية',
    bio: 'Lead UI/UX Designer',
    phone: '01123456789',
    device: 'لابتوب MacBook Pro',
    gender: 'أنثى',
    meeting_attendance: 'منتظم',
    work_status: 'active',
    can_go_alexandria: true,
  },
  {
    id: 3,
    created_at: new Date(Date.now() - 86400000 * 8).toISOString(),
    email: 'omar@wasla.com',
    full_name: 'عمر خالد',
    team: 'تطوير البرمجيات',
    completion_rank: 78,
    team_notes: 'يعمل على الـ Backend',
    residence: 'الجيزة - الدقي',
    work_conditions: 'عمل عن بعد',
    bio: 'Backend Engineer (Node.js & Supabase)',
    phone: '01234567890',
    device: 'كمبيوتر مكتبي (PC)',
    gender: 'ذكر',
    meeting_attendance: 'أحياناً',
    work_status: 'active',
    can_go_alexandria: false,
  },
  {
    id: 4,
    created_at: new Date(Date.now() - 86400000 * 7).toISOString(),
    email: 'mariam@wasla.com',
    full_name: 'مريم حسام',
    team: 'الميديا',
    completion_rank: 84,
    team_notes: 'مسؤولة عن المونتاج والتصوير',
    residence: 'الإسكندرية - لوران',
    work_conditions: 'متاحة للنزول الميداني',
    bio: 'Media & Video Production Lead',
    phone: '01512345678',
    device: 'لابتوب Core i5',
    gender: 'أنثى',
    meeting_attendance: 'منتظم',
    work_status: 'active',
    can_go_alexandria: true,
  },
  {
    id: 5,
    created_at: new Date(Date.now() - 86400000 * 6).toISOString(),
    email: 'youssef@wasla.com',
    full_name: 'يوسف إبراهيم',
    team: 'العلاقات العامة',
    completion_rank: 65,
    team_notes: 'تنسيق اللقاءات والشركاء',
    residence: 'القاهرة - مدينة نصر',
    work_conditions: 'متاح للنزول',
    bio: 'PR & Logistics Coordinator',
    phone: '01098765432',
    device: 'بدون جهاز',
    gender: 'ذكر',
    meeting_attendance: 'منتظم',
    work_status: 'active',
    can_go_alexandria: true,
  },
  {
    id: 6,
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    email: 'nourhan@wasla.com',
    full_name: 'نورهان طارق',
    team: 'الميديا',
    completion_rank: 70,
    team_notes: 'كتابة المحتوى وإدارة المنشورات',
    residence: 'القاهرة - مصر الجديدة',
    work_conditions: 'عمل عن بعد',
    bio: 'Creative Content Writer',
    phone: '01187654321',
    device: 'لابتوب',
    gender: 'أنثى',
    meeting_attendance: 'أونلاين فقط',
    work_status: 'active',
    can_go_alexandria: false,
  },
];

export const DEFAULT_TASKS: Task[] = [
  {
    id: 1,
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    title: 'تصميم واجهة لوحة تحكم وصلة (v2)',
    description: 'تجهيز وتنسيق واجهات لوحة التحكم الإدارية وبوابة الأعضاء، وضمان التوافق مع الهواتف الذكية.',
    has_deadline: true,
    deadline_date: '2026-10-05',
    assigned_to: ['2'],
    tracking: {
      '2': {
        status: 'under_review',
        note: 'تم الانتهاء من تصميم كافة الشاشات والمودالات، بانتظار مراجعة واعتماد الإدارة.',
        submission_url: 'https://figma.com/file/wasla-v2-mockup',
        updated_at: new Date(Date.now() - 3600000 * 4).toISOString(),
      },
    },
  },
  {
    id: 2,
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    title: 'ربط واجهات برمجة التطبيقات ونظام المصادقة',
    description: 'بناء دوال الاتصال مع Supabase وتأمين جلسات الدخول للإدارة والأعضاء.',
    has_deadline: true,
    deadline_date: '2026-10-12',
    assigned_to: ['1', '3'],
    tracking: {
      '1': {
        status: 'in_progress',
        note: 'جاري العمل على ربط جداول المهام والملاحظات.',
        updated_at: new Date(Date.now() - 3600000 * 2).toISOString(),
      },
      '3': {
        status: 'pending',
        updated_at: new Date(Date.now() - 86400000).toISOString(),
      },
    },
  },
  {
    id: 3,
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    title: 'تجهيز خطة التغطية الإعلامية لاجتماع الإسكندرية',
    description: 'إعداد جدول المقابلات والتصوير الفوتوغرافي ومعدات الصوت أثناء الاجتماع الميداني.',
    has_deadline: false,
    deadline_date: null,
    assigned_to: ['4'],
    tracking: {
      '4': {
        status: 'approved',
        note: 'تم إعداد الخطة واعتمادها بالكامل.',
        submission_url: 'https://drive.google.com/wasla-media-plan',
        updated_at: new Date(Date.now() - 86400000 * 2).toISOString(),
      },
    },
  },
  {
    id: 4,
    created_at: new Date(Date.now() - 86400000).toISOString(),
    title: 'حصر أجهزة وتواجد الفريق للنزول الميداني',
    description: 'مراجعة وتأكيد توافر أجهزة اللابتوب والقدرة على السفر والإقامة في الإسكندرية.',
    has_deadline: true,
    deadline_date: '2026-10-02',
    assigned_to: 'ALL',
    tracking: {
      '1': { status: 'approved', updated_at: new Date().toISOString() },
      '2': { status: 'approved', updated_at: new Date().toISOString() },
      '3': { status: 'in_progress', note: 'أحاول تأمين لابتوب إضافي', updated_at: new Date().toISOString() },
      '4': { status: 'approved', updated_at: new Date().toISOString() },
      '5': { status: 'pending', updated_at: new Date().toISOString() },
      '6': { status: 'pending', updated_at: new Date().toISOString() },
    },
  },
];
